// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpgbupisahyxtrnhqphd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wZ2J1cGlzYWh5eHRybmhxcGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MDU1MDksImV4cCI6MjA1NzA4MTUwOX0.G_Cumf_qpV4pttW0h1H9T6lQSy3AAoSQULtI2vgR8ig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);